development:
  adapter: postgresql 
  database: forocoches_poles
  encoding: unicode 
  pool: 5
  username: alice
  password: password
  host: localhost


production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: somedatabase_dev
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

test: &test
  adapter: postgresql 
  database: forocoches_poles_test
  encoding: utf8
  pool: 5
  username: alice
  password: password
  host: localhost
